### ISSUE TITLE
following the instructions, not able to connect to zookeeper

### ISSUE THREAD

**Issue by spatzle** [makuk66/docker-solr#1]
Hi 

I was able to get zookeeper up and running, and tested that it works on port 2181, and so forth, but then when I try to run docker-solr in solrCloud mode, it's not able to connect to zookeeper.  Any ideas why that may be?

 WARN  org.apache.zookeeper.ClientCnxn  – Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused

However, solrCloud by itself w/o the use of docker, does work with the docker-zookeeper.

Many thanks for your help
Joyce

**Comment by makuk66** [comment]
Joyce, from your description I cannot tell what the problem is.

I have updated the instructions for 5.0, and they work for me; please try again.
