### ISSUE TITLE
Reduce image size

### ISSUE THREAD

**Issue by ericcitaire** [makuk66/docker-solr#11]
- use JRE instead of JDK (275 MB). Solr documentation encourages to install JDK for full international charset support, but I'm pretty sure this is an obsolete requirement, see [Java 8 Supported Encodings](https://docs.oracle.com/javase/8/docs/technotes/guides/intl/encoding.doc.html).
- don't install lsof (38 MB) which is not needed. By the way, curl and procps are not needed and are already installed. The hole apt-get install command can be entirely removed.

**Comment by ericcitaire** [comment]
In addition, [Solr 5 documentation](https://cwiki.apache.org/confluence/display/solr/Installing+Solr) says you only need a JRE.

**Comment by makuk66** [comment]
> use JRE instead of JDK

Now that we use official `java:8` parent image, I'm less concerned about the size premium of the JDK -- you only pay cost that once, and it is shared over other images that reference it. The `java:8` doesn't even specify a preference, and I picked that to increase the chances of re-use.

But, I'm not opposed to changing this and follow the docs recommendation explicitly.

> don't install lsof (38 MB) which is not needed. 

It is used here: https://github.com/apache/lucene-solr/blob/trunk/solr/bin/solr#L1321

> By the way, curl and procps are not needed and are already installed.

Ah, handy.
