### ISSUE TITLE
how to reach schema.xml and solrconfig.xml inside collection

### ISSUE THREAD

**Issue by althunibat** [makuk66/docker-solr#13]
i have run solr cloud with zookeeper as explained.
i'm now stuck with editing the xml files, usually i ssh to the solr machine from my laptop.

**Comment by rposborne** [comment]
+1

**Comment by nullren** [comment]
you don't edit those through solr. upload the updated schema and solrconfig to zookeeper, then use the [collections API](https://cwiki.apache.org/confluence/display/solr/Collections+API) to [reload](https://cwiki.apache.org/confluence/display/solr/Collections+API#CollectionsAPI-api2) the collection.

**Comment by makuk66** [comment]
Thanks @nullren
