### ISSUE TITLE
FAQ.md needs better explanation

### ISSUE THREAD

**Issue by abbi-gaurav** [makuk66/docker-solr#14]
I had a chance to look at the FAQ file and in the section

How can I mount a host directory as a data volume?

I donot see any relevance for this step
# copy the solr directory from a temporary container to the volume

$ docker run -it --rm -v /home/docker-volumes/mysolr1:/target makuk66/docker-solr cp -r server/solr /target/

Could you please add the reason for doing this?
If this is  not needed, please delete it to avoid confusion.

**Comment by makuk66** [comment]
That step is required. The preceding paragraph explains why. I've modified it slightly in case that helps.

If you are still not sure, can tell me what specifically is unclear?
