### ISSUE TITLE
Yo this readme sucks either fix and update your shit it or deprecate this repo. You haven't made a commit since October. 

### ISSUE THREAD

**Issue by frangucc** [makuk66/docker-solr#15]
If you're still active I'll submit a pull request but your readme doesn't even work not sure if you're the right guy to run this repo.

**Comment by b-long** [comment]
Be nice.  See here: https://github.com/docker-solr/docker-solr

**Comment by irnnr** [comment]
Wow, you're an a-hole @frangucc
