### ISSUE TITLE
Tag image at 151e7f0 as 4.10.3.

### ISSUE THREAD

**Issue by mparker17** [makuk66/docker-solr#2]
Commit d09a40b3e50124b4da5dba7cb81f88b0ce2328a7 upgraded Apache Solr to version 5.0.0, but not all of my applications are ready for that yet.

The Dockerfile specification says you can use a tag in the `FROM` command, but it looks like the maintainer of the image on the Docker Hub has to manually tag it — Docker doesn't appear to let you use a Build ID or commit hash as a tag.

If you were able to checkout 151e7f03b97d61d9ce4f701f9d8f92d183eb4831, build the image, tag it, and push that tag to [the image on the Docker hub](https://registry.hub.docker.com/u/makuk66/docker-solr/) as `4.10.3`, then I could modify my Dockerfile to say `FROM makuk66/docker-solr:4.10.3` until I was ready to upgrade to `makuk66/docker-solr:latest`.

More information about tagging images is available here: https://docs.docker.com/userguide/dockerimages/#setting-tags-on-an-image

**Comment by bufke** [comment]
+1 solr 5 introduces a number of backwards incompatible changes.

**Comment by t0xicCode** [comment]
:+1:

**Comment by makuk66** [comment]
Done:

```
$ docker run -it makuk66/docker-solr:4.10.3 bash -c "ls /opt/solr/dist/solr-core-*.jar"
/opt/solr/dist/solr-core-4.10.3.jar
$ docker run -it makuk66/docker-solr:latest bash -c "ls /opt/solr/dist/solr-core-*.jar"
/opt/solr/dist/solr-core-5.0.0.jar
```

**Comment by mparker17** [comment]
Awesome, thanks very much @makuk66 ! :smile:
