### ISSUE TITLE
Instructions are incomplete for single node

### ISSUE THREAD

**Issue by dimitrovs** [makuk66/docker-solr#6]
In the instructions you explain how to create a collection for cloud deployment, but not how to create a core in single node (default) mode. Without a core Solr is useless. Using the admin interface I was not able to create a core, but I managed to do it with exec:

bin/solr create_core -c gettingstarted

I think it will be helpful to add this line to the instructions, for people who are trying out Solr for the first time.

**Comment by makuk66** [comment]
As elwebmaster says:

> Without a core Solr is useless.

Right. Solr used to come with a default collection, but not anymore.

> Using the admin interface I was not able to create a core

There is an issue open for that: [SOLR-4461](https://issues.apache.org/jira/browse/SOLR-4461) 

> I think it will be helpful to add this line to the instructions

Agreed. I've added that, plus some data loading examples.

Thanks for your suggestion
