### ISSUE TITLE
Document how to make a persistent storage

### ISSUE THREAD

**Issue by sobrinho** [makuk66/docker-solr#9]
Which directory should be mounted as volume to persist the data?

**Comment by amalagaura** [comment]
I am trying to figure out the same thing.

I am looking at the README.txt in /opt/solr/server/solr and it says

```
* Core Discovery *

During startup, Solr will scan sub-directories of Solr home looking for
a specific file named core.properties. If core.properties is found in a
sub-directory (at any depth), Solr will initialize a core using the properties
defined in core.properties. For an example of core.properties, please see:

example/solr/collection1/core.properties
```

So I think we can initialize some cores and share them to that directory to get the persistent cores.

**Comment by makuk66** [comment]
@sobrinho, @amalagaura have a look at https://github.com/makuk66/docker-solr/commit/6849cf652cd694cae8ae5048125e831eae9f172c
